version: "3.9"

services:
  auth-service-api:
    image: auth-service:${COMMIT:-unknown}
    container_name: auth-service-api
    depends_on:
      - auth-service-db
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    build:
      context: .
    environment:
      DB_HOST: auth-service-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME:?dbNameNotProvided}
      DB_USER: ${DB_USER:?dbUserNotProvided}
      DB_PASSWORD: ${DB_PASSWORD:?dbPasswordNotProvided}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?dbRootPasswordNotProvided}
      HTTP_PORT: ${HTTP_PORT?:httpPortNotProvided}
      GRPC_PORT: ${GRPC_PORT?:grpcPortNotProvided}
      JWT_SECRET_ACCESS: ${JWT_SECRET_ACCESS?:jwtSecretAccessNotProvided}
      JWT_SECRET_REFRESH: ${JWT_SECRET_REFRESH?:jwtSecretRefreshNotProvided}
    restart: unless-stopped
  auth-service-db:
    container_name: auth-service-db
    image: 'mysql:latest'

    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USER}'
    restart: unless-stopped